apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
      app: node-api
  type: LoadBalancer
  ports:
        - name: nodeapi-port
          port: 80
          targetPort: 3000