apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabels:
      app: node-api
  replicas: 2
  template:
    metadata:
      labels:
        app: node-api
    spec:
        containers:
        - name: nodeapifork8s 
          image: hvglabacr.azurecr.io/nodeapifork8s:V1 
          ports:
            - containerPort: 80